# config/manifest.yml
project:
  name: "PamChip Kinome Array Annotation Pipeline"
  version: "4.6.1"

chip:
  name: "PamGene STK 87202"
  type: "STK"
  file: "data/raw/87202-Array-Layout.csv"

sources:
  signor:
    force_update: false
  gps6:
    threshold: "high" # Options: low, medium, high
  kinase_library:
    cutoff: 0.90 # Percentile score threshold for PSSM predictions

mapping_weights:
  signor: 0.50          # Weight given to experimentally validated interactions
  gps6: 0.25            # Weight given to GPS 6.0 predictions
  kinase_library: 0.25  # Weight given to The Kinase Library PSSM matrix predictions
