#' Export PamChip Peptide Sequences to FASTA for GPS 6.0
#'
#' @param sites Parsed PamChip sites tibble from parse_pamchip_annotations()
#' @param output_path File path for generated FASTA
#' @return Path to written FASTA file
export_chip_fasta <- function(sites, output_path) {
  dir.create(dirname(output_path), recursive = TRUE, showWarnings = FALSE)
  
  # Prepare distinct sequence entries
  fasta_df <- sites %>%
    dplyr::distinct(id, uniprot_id, sequence_fragment)
  
  fasta_lines <- unlist(lapply(seq_len(nrow(fasta_df)), function(i) {
    c(
      paste0(">", fasta_df$id[i], "|", fasta_df$uniprot_id[i]), 
      fasta_df$sequence_fragment[i]
    )
  }))
  
  writeLines(fasta_lines, output_path)
  return(output_path)
}


#' Run GPS 6.0 Command Line Interface (CLI)
#'
#' Executes GPS 6.0 kinase-substrate prediction tool on a FASTA input file.
#' Supports local project binaries, container paths, and headless Qt mode.
#'
#' @param fasta_path Path to input FASTA file generated by export_chip_fasta()
#' @param out_dir Output directory path passed from targets pipeline
#' @param output_path Alternative target output file path (if out_dir is not set)
#' @param gps_path Path or command name for GPS executable / JAR.
#' @param threshold GPS prediction stringency threshold ("low", "medium", "high")
#' @return Path to output prediction file or output directory
run_gps6_cli <- function(fasta_path, 
                         out_dir = file.path("data", "external", "gps6"), 
                         output_path = NULL, 
                         gps_path = Sys.getenv("GPS6_PATH", unset = "GPS6"), 
                         threshold = "medium") {
  
  # Ensure headless environment variables are set for Qt GUI backends
  Sys.setenv(
    QT_QPA_PLATFORM = "offscreen",
    QT_LOGGING_RULES = "*=false",
    DISPLAY = ""
  )

  # Determine target directory and output file path
  target_dir <- if (!is.null(out_dir)) out_dir else dirname(output_path)
  dir.create(target_dir, recursive = TRUE, showWarnings = FALSE)

  final_output_file <- if (!is.null(output_path)) {
    output_path
  } else {
    file.path(target_dir, "gps6_predictions.txt")
  }

  if (!file.exists(fasta_path)) {
    stop("Input FASTA file not found at: ", fasta_path)
  }

  # Fast return if valid prediction output was already created
  if (file.exists(final_output_file) && file.size(final_output_file) > 1000) {
    message("Found existing valid GPS 6.0 output file: ", final_output_file)
    return(if (!is.null(out_dir)) out_dir else final_output_file)
  }

  # 1. Search for existing binary/jar across local project, PATH, and container paths
  local_bin_gps6 <- file.path(getwd(), "bin", "gps6", "GPS6")
  local_bin_gps60 <- file.path(getwd(), "bin", "gps6", "GPS6.0")

  extracted_files <- if (dir.exists("/opt/gps6")) {
    list.files("/opt/gps6", full.names = TRUE, recursive = TRUE)
  } else {
    character(0)
  }

  # 2. Extract package from tarball if missing from all locations
  tarball <- "/opt/gps6/GPS_6.0_unix_20230422.tar.gz"
  if (length(extracted_files) == 0 && 
      file.exists(tarball) && 
      file.size(tarball) > 100000 &&
      !file.exists(local_bin_gps6) && 
      !file.exists(local_bin_gps60)) {
    
    message("Extracting GPS 6.0 package from ", tarball, "...")
    system(sprintf("tar -xzf %s -C /opt/gps6/", shQuote(tarball)), ignore.stdout = TRUE, ignore.stderr = TRUE)
    extracted_files <- list.files("/opt/gps6", full.names = TRUE, recursive = TRUE)
  }

  # 3. Resolve executable candidate
  candidate_bins <- c(
    gps_path,
    Sys.which(gps_path),
    local_bin_gps6,
    local_bin_gps60,
    grep("GPS6$|GPS6\\.0$|GPS.*6.*|.*\\.jar$", extracted_files, value = TRUE, ignore.case = TRUE)
  )

  candidate_bins <- candidate_bins[
    !dir.exists(candidate_bins) & 
    !endsWith(candidate_bins, ".tar.gz") & 
    !endsWith(candidate_bins, ".zip") &
    !endsWith(candidate_bins, ".tar")
  ]

  resolved_bin <- NULL
  for (cand in candidate_bins) {
    if (nzchar(cand) && file.exists(cand) && file.size(cand) > 5000) {
      resolved_bin <- cand
      break
    }
  }

  if (is.null(resolved_bin)) {
    stop(
      "GPS 6.0 executable or JAR could not be located.\n",
      "Please ensure 'bin/gps6/GPS6' exists in your project directory or pass 'GPS6_PATH'."
    )
  }

  message("Executing GPS 6.0 CLI prediction using: ", resolved_bin)

  # Grant execution permissions for binary files
  if (!endsWith(resolved_bin, ".jar")) {
    Sys.chmod(resolved_bin, mode = "0755")
  }

  # Construct base execution command
  base_cmd <- if (endsWith(resolved_bin, ".jar")) {
    sprintf(
      "java -jar %s -i %s -o %s -t %s",
      shQuote(resolved_bin),
      shQuote(fasta_path),
      shQuote(final_output_file),
      shQuote(threshold)
    )
  } else {
    sprintf(
      "%s -i %s -o %s -t %s",
      shQuote(resolved_bin),
      shQuote(fasta_path),
      shQuote(final_output_file),
      shQuote(threshold)
    )
  }

  # Wrap command with timeout to prevent PyInstaller/Qt shutdown hangs
  cmd <- sprintf("timeout 600s %s || true", base_cmd)
  
  system(cmd)

  # Validate created prediction file
  if (!file.exists(final_output_file) || file.size(final_output_file) == 0) {
    stop("GPS 6.0 CLI failed to generate output file at: ", final_output_file)
  }

  message("GPS 6.0 prediction successfully completed! Output size: ", file.size(final_output_file), " bytes.")
  return(if (!is.null(out_dir)) out_dir else final_output_file)
}
